require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe ShoppingListsController, type: :controller do
  before(:each) do
    @store = Store.create(name: "store")
    @user = User.create(email: "test@example.com", password: "password")
  end


  let(:valid_attributes) {
    {
      store: @store,
      user: @user,
      date: Time.now,
      time: Time.now
    }
  }

  let(:invalid_attributes) {
    {
      store: nil,
      date: Time.now,
      time: Time.now
    }
  }

  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      shopping_list = ShoppingList.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      shopping_list = ShoppingList.create! valid_attributes
      get :show, params: {id: shopping_list.to_param}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #new" do
    login_user
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #edit" do
    login_user
    it "returns a success response" do
      shopping_list = ShoppingList.create! valid_attributes
      get :edit, params: {id: shopping_list.to_param}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    login_user
    context "with valid params" do
      skip it "creates a new ShoppingList" do
        expect {
          post :create, params: {shopping_list: valid_attributes, user_id: current_user}, session: valid_session
        }.to change(ShoppingList, :count).by(1)
      end

      skip it "redirects to the created shopping_list" do
        post :create, params: {shopping_list: valid_attributes}, session: valid_session
        expect(response).to redirect_to(ShoppingList.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {shopping_list: invalid_attributes}, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe "PUT #update" do
    login_user
    context "with valid params" do
      @store2 = Store.create(name: "store 2")
      newtime = Time.now
      let(:new_attributes) {
        {
          store: @store2
        }
      }

      it "updates the requested shopping_list" do
        shopping_list = ShoppingList.create! valid_attributes
        put :update, params: {id: shopping_list.to_param, shopping_list: new_attributes}, session: valid_session
        shopping_list.reload
        expect(shopping_list.store).to eql(@store2)
      end

      skip it "redirects to the shopping_list" do
        shopping_list = ShoppingList.create! valid_attributes
        put :update, params: {id: shopping_list.to_param, shopping_list: valid_attributes}, session: valid_session
        expect(response).to redirect_to(shopping_list)
      end
    end

    context "with invalid params" do
      skip it "returns a success response (i.e. to display the 'edit' template)" do
        shopping_list = ShoppingList.create! valid_attributes
        put :update, params: {id: shopping_list.to_param, shopping_list: invalid_attributes}, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe "DELETE #destroy" do
    login_user
    it "destroys the requested shopping_list" do
      shopping_list = ShoppingList.create! valid_attributes
      expect {
        delete :destroy, params: {id: shopping_list.to_param}, session: valid_session
      }.to change(ShoppingList, :count).by(-1)
    end

    it "redirects to the shopping_lists list" do
      shopping_list = ShoppingList.create! valid_attributes
      delete :destroy, params: {id: shopping_list.to_param}, session: valid_session
      expect(response).to redirect_to(shopping_lists_url)
    end
  end

end
